del test.uc2
fa *.tqq /clean
echo hallo > H---.tqq
echo hallo > ----.tqq
echo hallo > HS--.tqq
echo hallo > -S--.tqq
echo hallo > H-R-.tqq
echo hallo > --R-.tqq
echo hallo > HSR-.tqq
echo hallo > -SR-.tqq
echo hallo > H--A.tqq
echo hallo > ---A.tqq
echo hallo > HS-A.tqq
echo hallo > -S-A.tqq
echo hallo > H-RA.tqq
echo hallo > --RA.tqq
echo hallo > HSRA.tqq
echo hallo > -SRA.tqq
fa *.tqq /a-
fa h???.tqq /hid+
fa ?s??.tqq /sys+
fa ??r?.tqq /r+
fa ???a.tqq /a+
fa *.tqq
